name: Check for new coiled-runtime version

on:
  schedule:
    - cron: "36 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository == 'coiled/software-environments'

    steps:
      - uses: actions/checkout@v2
      - name: Get latest coiled-runtime version
        id: latest_version
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.1
        with:
          # TODO: Update to conda-forge once coiled-runtime is available there
          org: "coiled"
          package: "coiled-runtime"

      - name: Find and replace coiled-runtime version
        id: find_and_replace
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          find: "coiled-runtime=[.0-9]+"
          replace: "coiled-runtime=${{ steps.latest_version.outputs.version }}"

      - name: Output changed files
        run: echo ${{ steps.find_and_replace.outputs.modifiedFiles }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update coiled-runtime version to ${{ steps.latest_version.outputs.version }}"
          title: "Update coiled-runtime version to ${{ steps.latest_version.outputs.version }}"
          reviewers: "jrbourbeau"
          branch: "upgrade-package-versions"
          body: |
            A new coiled-runtime version has been detected.

            Updated coiled-runtime to `${{ steps.latest_version.outputs.version }}`.
