
name: Update software environments

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        software-env: ["default-py36", "default-py37", "default-py38", "default"]
        include:
          - software-env: "default-py36"
            env-file: default/environment-py36.yml

          - software-env: "default-py37"
            env-file: default/environment-py37.yml

          - software-env: "default-py38"
            env-file: default/environment-py38.yml

          - software-env: "default"
            env-file: default/environment-py38.yml
    env:
      DASK_COILED__SERVER: https://cloud.coiled.io
      DASK_COILED__TOKEN: ${{ secrets.DASK_COILED__TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build ${{ matrix.software-env }} software environment 
        run: coiled env create --name coiled/${{ matrix.software-env }} --conda ${{ matrix.env-file }}