name: Update software environments

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        software-env:
          ["default-py37", "default-py38", "default-py39", "default-py310", "default"]
        server: ["https://cloud.coiled.io", "https://staging.coiledhq.com", "https://development.coiledhq.com"]
        include:
          - software-env: "default-py37"
            env-file: default/environment-py37.yml

          - software-env: "default-py38"
            env-file: default/environment-py38.yml

          - software-env: "default-py39"
            env-file: default/environment-py39.yml

          - software-env: "default-py310"
            env-file: default/environment-py310.yml

          - software-env: "default"
            env-file: default/environment-py39.yml

          - server: "https://cloud.coiled.io"
            token-name: CLOUD_TOKEN

          - server: "https://staging.coiledhq.com"
            token-name: SANDBOX_TOKEN

          - server: "https://development.coiledhq.com"
            token-name: DEV_TOKEN

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build ${{ matrix.software-env }} software environment
        env:
          DASK_COILED__SERVER: ${{ matrix.server }}
          DASK_COILED__TOKEN: ${{ secrets[matrix.token-name] }}
        run: coiled env create --name coiled/${{ matrix.software-env }} --conda ${{ matrix.env-file }}
