
name: Update software environments

on:
  push:
    branches: main
  # TODO: Remove pull_request builds
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        software-env: ["default-py36", "default-py37", "default-py38", "default"]
        server: ["https://cloud.coiled.io", "https://sandbox.coiledhq.com"]
        include:
          - software-env: "default-py36"
            env-file: default/environment-py36.yml

          - software-env: "default-py37"
            env-file: default/environment-py37.yml

          - software-env: "default-py38"
            env-file: default/environment-py38.yml

          - software-env: "default"
            env-file: default/environment-py38.yml
          
          - server: "https://cloud.coiled.io"
            token: ${{ secrets.CLOUD_TOKEN }}

          - server: "https://sandbox.coiledhq.com"
            token: ${{ secrets.SANDBOX_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build ${{ matrix.software-env }} software environment 
        env:
          DASK_COILED__SERVER: ${{ matrix.server }}
          DASK_COILED__TOKEN: ${{ matrix.token }}
        run: coiled env create --name coiled/${{ matrix.software-env }} --conda ${{ matrix.env-file }}